services:
  nordpool:
    build: .
    restart: always
    networks:
      - proxy
    labels:
      - caddy=nordpool.azib.net
      - caddy.reverse_proxy={{upstreams 7070}}
      - caddy.reverse_proxy.lb_retries=5
      - caddy.reverse_proxy.lb_try_interval=500ms

networks:
  proxy:
    external: true
