services:
  nordpool:
    build: .
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nordpool.rule=Host(`nordpool.azib.net`)"
      - "traefik.http.routers.nordpool.entrypoints=websecure"
      - "traefik.http.routers.nordpool.tls.certresolver=letsencrypt"

networks:
  proxy:
    external: true
